version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: fix
      prefix-development: fix
      include: scope
    reviewers:
      - cewald
