version: 2
registries:
  cewald:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.NPM_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - cewald
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
    groups:
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: fix
      prefix-development: fix
      include: scope
