# christianewald.de
[[redirects]]
  from = "https://christianewald.de"
  to = "https://ewaldewald.com"
  status = 301
  force = true
[[redirects]]
  from = "https://christianewald.de/*"
  to = "https://ewaldewald.com/:splat"
  status = 301
[[redirects]]
  from = "https://www.christianewald.de"
  to = "https://ewaldewald.com"
  status = 301
  force = true
[[redirects]]
  from = "https://www.christianewald.de/*"
  to = "https://ewaldewald.com/:splat"
  status = 301

# cewald.de
[[redirects]]
  from = "https://cewald.de"
  to = "https://ewaldewald.com"
  status = 301
  force = true
[[redirects]]
  from = "https://cewald.de/*"
  to = "https://ewaldewald.com/:splat"
  status = 301
[[redirects]]
  from = "https://www.cewald.de"
  to = "https://ewaldewald.com"
  status = 301
  force = true
[[redirects]]
  from = "https://www.cewald.de/*"
  to = "https://ewaldewald.com/:splat"
  status = 301

# ewald.codes
[[redirects]]
  from = "https://ewald.codes"
  to = "https://ewaldewald.com"
  status = 301
  force = true
[[redirects]]
  from = "https://ewald.codes/*"
  to = "https://ewaldewald.com/:splat"
  status = 301
[[redirects]]
  from = "https://www.ewald.codes"
  to = "https://ewaldewald.com"
  status = 301
  force = true
[[redirects]]
  from = "https://www.ewald.codes/*"
  to = "https://ewaldewald.com/:splat"
  status = 301

# ewaldewald.me
[[redirects]]
  from = "https://ewaldewald.me"
  to = "https://ewaldewald.com"
  status = 301
  force = true
[[redirects]]
  from = "https://ewaldewald.me/*"
  to = "https://ewaldewald.com/:splat"
  status = 301
[[redirects]]
  from = "https://www.ewaldewald.me"
  to = "https://ewaldewald.com"
  status = 301
  force = true
[[redirects]]
  from = "https://www.ewaldewald.me/*"
  to = "https://ewaldewald.com/:splat"
  status = 301

# Default Settings
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "public,max-age=31536000"
