version: '3.0'
services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - '../:/var/www'
    tmpfs:
      - /var/www/dist
    ports:
      - '3000:3000'
    entrypoint: /bin/sh
    command: [ "-c", "while sleep 1000; do :; done" ]
